apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.13.2
        ports:
          - containerPort: 5601
        env:
          - name: SERVER_NAME
            value: http://kibana.flou21.de
          - name: ELASTICSEARCH_HOSTS
            value: https://elastic.flou21.de
          - name: ELASTICSEARCH_USERNAME
            valueFrom: 
              configMapKeyRef:
                name: elastic-config
                key: username
          - name: ELASTICSEARCH_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: elastic-secret
                key: password
        resources:
          requests:
            memory: "1000Mi"
            cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: elastic
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort:  5601