apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data-claim
  namespace: elastic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

