apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: damlo
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: frontend
        image: registry.flou21.de/damlo:1d38860d-d2f5-4ac7-8348-723a47af00ed
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: damlo
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
