apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: damlo
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: frontend
        image: registry.flou21.de/damlo:38f980f9-00ae-4138-b090-db2284a07f1f
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: damlo
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
