enabled: true

replicaCount: 3
revisionHistoryLimit: 5

image:
  repository: muehlhansfl/hypixel-react
  tag: dbf8c343bd168105c0b97a86915aad20d21aff90@sha256:ef32852036ca7893c0bdf1488aba00a6279b0cddbeb2c741468d0d3e0c9782aa
  pullPolicy: IfNotPresent

ports:
  - name: web
    containerPort: 3000

resources:
  requests:
    cpu: 150m
    memory: 500Mi

serivcePorts:
  - name: web
    port: 3000
    targetPort: 3000

readinessProbe:
  httpGet:
    path: /
    port: web
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 6
  timeoutSeconds: 5

envVars:
  - name: COMMAND_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: config
        key: frontend_command_endpoint
  - name: API_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: config
        key: frontend_api_endpoint

ingress:
  enabled: false
  nginx: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
