enabled: true

replicaCount: 3
revisionHistoryLimit: 5

image:
  repository: muehlhansfl/hypixel-react
  tag: 3130ad1fef72fd594907786263a87fc1bb78bbda@sha256:c396d7cbaa6d9901337d03bd14468bb4f08a1406b4f37b99574fefd8c9146365
  pullPolicy: IfNotPresent

ports:
  - name: web
    containerPort: 3000

resources:
  requests:
    cpu: 350m
    memory: 500Mi

serivcePorts:
  - name: web
    port: 3000
    targetPort: 3000

readinessProbe:
  httpGet:
    path: /
    port: web
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 6
  timeoutSeconds: 5

envVars:
  - name: COMMAND_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: config
        key: frontend_command_endpoint
  - name: API_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: config
        key: frontend_api_endpoint

ingress:
  enabled: false
  nginx: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
