enabled: true

replicaCount: 3
revisionHistoryLimit: 5

image:
  repository: muehlhansfl/hypixel-react
  tag: a336cc5a7d92d33f701105c146902af990b245b6@sha256:09b0742af79a27d3c302f25eba12c6446b26d8244ebec1ecda5f798bfcf3e776
  pullPolicy: IfNotPresent

ports:
  - name: web
    containerPort: 3000

resources:
  requests:
    cpu: 350m
    memory: 500Mi

serivcePorts:
  - name: web
    port: 3000
    targetPort: 3000

readinessProbe:
  httpGet:
    path: /
    port: web
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 6
  timeoutSeconds: 5

envVars:
  - name: COMMAND_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: config
        key: frontend_command_endpoint
  - name: API_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: config
        key: frontend_api_endpoint

ingress:
  enabled: false
  nginx: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
