apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-temp-env
  namespace: argo
spec:
  serviceAccountName: argo-events-sa
  templates:
  - name: create-temp-env
    inputs:
      parameters:
        - name: pull_request_new_state
        - name: pull_request_number
        - name: git_repository
        - name: git_username
        - name: git_password_secret_name
        - name: git_password_secret_key
        - name: template_data_deployment_name
        - name: template_data_namespace
        - name: template_data_app_label
        - name: template_data_container_tag
        - name: template_data_container_image
        - name: template_data_container_name
        - name: template_data_port
        - name: template_data_memory
        - name: template_data_cpu
        - name: template_data_domain_name
    container:
      image: registry.flou21.de/temp-env:latest
      imagePullPolicy: Always
      env:
        - name: PULL_REQUEST_NEW_STATE
          value: "{{inputs.parameters.pull_request_new_state}}"
        - name: PULL_REQUEST_NUMBER
          value: "{{inputs.parameters.pull_request_number}}"
        - name: GIT_REPOSITORY
          value: "{{inputs.parameters.git_repository}}"
        - name: GIT_USERNAME
          value: "{{inputs.parameters.git_username}}"
        - name: GIT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: "{{inputs.parameters.git_password_secret_name}}"
              key: "{{inputs.parameters.git_password_secret_key}}"
        - name: TEMPLATE_DATA_DEPLOYMENT_NAME
          value: "{{inputs.parameters.template_data_deployment_name}}"
        - name: TEMPLATE_DATA_NAMESPACE
          value: "{{inputs.parameters.template_data_namespace}}"
        - name: TEMPLATE_DATA_APP_LABEL
          value: "{{inputs.parameters.template_data_app_label}}"
        - name: TEMPLATE_DATA_CONTAINER_TAG
          value: "{{inputs.parameters.template_data_container_tag}}"
        - name: TEMPLATE_DATA_CONTAINER_NAME
          value: "{{inputs.parameters.template_data_container_name}}"
        - name: TEMPLATE_DATA_CONTAINER_IMAGE
          value: "{{inputs.parameters.template_data_container_image}}"
        - name: TEMPLATE_DATA_PORT
          value: "{{inputs.parameters.template_data_port}}"
        - name: TEMPLATE_DATA_MEMORY
          value: "{{inputs.parameters.template_data_memory}}"
        - name: TEMPLATE_DATA_CPU
          value: "{{inputs.parameters.template_data_cpu}}"
        - name: TEMPLATE_DATA_DOMAIN_NAME
          value: "{{inputs.parameters.template_data_domain_name}}"
