apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
    name: cypress-tests-chrome91
    namespace: argo
spec:
    serviceAccountName: argo-events-sa
    templates:
    - name: cypress-tests-chrome91
      inputs:
        parameters:
          - name: git_repository
          - name: spec
      container:
        image: registry.flou21.de/cypress-runner:chrome91
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1500Mi
            cpu: 1000m
        args:
        - /app
        - --repository="{{inputs.parameters.git_repository}}"
        - --branch="master"
        - --browser=chrome
        - --spec="{{inputs.parameters.spec}}"