enabled: true
replicaCount: 1

strategy: Recreate

image:
  repository: muehlhansfl/skyindexer
  tag: cf81aa7f1dffb8dd80af6894b4306542b810d54c@sha256:59858ad26e338515c1b343d713fa1d6b5c3c629e5b11447689ec4ad3b0fd9139
  pullPolicy: IfNotPresent

ports:
  - name: api
    containerPort: 8000

resources:
  requests:
    cpu: 150m
    memory: 550Mi
  limits:
    cpu: 500m
    memory: 700Mi

serivcePorts:
  - name: api
    port: 8000
    targetPort: 8000

readinessProbe:
  httpGet:
    path: /api/index.html
    port: api
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 10

envVars:
  - name: DBConnection
    valueFrom:
      secretKeyRef:
        key: connection_live
        name: secret
  - name: SKYCOMMANDS_HOST
    valueFrom:
      configMapKeyRef:
        name: config
        key: commands_host
