enabled: true
replicaCount: 1

strategy: Recreate

image:
  repository: muehlhansfl/skyindexer
  tag: b412bb2383777ef6d1ab53d63fbbf36580b6ce05@sha256:7308cd54d199d54c3d9398b99c3b39881ef837d2f2f9a3bdff6eb10a81f9cb0a
  pullPolicy: IfNotPresent

ports:
  - name: api
    containerPort: 8000

resources:
  requests:
    cpu: 150m
    memory: 550Mi
  limits:
    cpu: 500m
    memory: 700Mi

serivcePorts:
  - name: api
    port: 8000
    targetPort: 8000

readinessProbe:
  httpGet:
    path: /api/index.html
    port: api
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 10

envVars:
  - name: DBConnection
    valueFrom:
      secretKeyRef:
        key: connection_live
        name: secret
  - name: SKYCOMMANDS_HOST
    valueFrom:
      configMapKeyRef:
        name: config
        key: commands_host
