apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sky-webhook-pull-request
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: sky-eventsource
    eventName: sky-pull-request
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        parameters:
          - src: 
              dependencyName: payload
              dataKey: body.action
            dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
          - src: 
              dependencyName: payload
              dataKey: body.number
            dest: spec.templates.0.dag.tasks.0.arguments.parameters.1.value
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              namespace: argo
              generateName: create-temp-env
              labels:
                workflows.argoproj.io/archive-strategy: "false"
            spec:
              entrypoint: create-temp-env
              serviceAccountName: argo
              imagePullSecrets:
                - name: regcred
              volumes:
              - name: kaniko-secret
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: sky-argo-secret
                secret:
                  secretName: sky-argo-secret
              templates:
              - name: create-temp-env
                dag:
                  tasks:
                  - name: create-temp-env
                    templateRef:
                      name: create-temp-env
                      template: create-temp-env
                    arguments:
                      parameters:
                        - name: pull_request_new_state
                          value: ""
                        - name: pull_request_number
                          value: ""
                        - name: git_repository
                          value: "github.com/Flou21/k8s"
                        - name: git_username
                          value: "Flou21"
                        - name: git_password_secret_name
                          value: "secret"
                        - name: git_password_secret_key
                          value: "password"
                        - name: k8s_namespace
                          value: "sky"
                        - name: container_image
                          value: "light-client"
                        - name: "container_port"
                          value: "8008"
                        - name: request_memory
                          value: "100Mi"
                        - name: request_cpu
                          value: "100m"
                        - name: base_domain
                          value: "flou21.de"