apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sky-webhook-pull-request
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: sky-pull-request
    eventSourceName: sky-eventsource
    eventName: sky-pull-request
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              namespace: argo
              generateName: create-temp-env
              labels:
                workflows.argoproj.io/archive-strategy: "false"
            spec:
              entrypoint: create-temp-env
              serviceAccountName: argo
              imagePullSecrets:
                - name: regcred
              volumes:
              - name: kaniko-secret
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: sky-argo-secret
                secret:
                  secretName: sky-argo-secret
              templates:
              - name: create-temp-env
                dag:
                  tasks:
                  - name: create-temp-env
                    templateRef:
                      name: create-temp-env
                      template: create-temp-env
                    arguments:
                      parameters:
                        - name: pull_request_new_state
                          value: "{{inputs.parameters.action}}"
                        - name: pull_request_number
                          value: "300"
                        - name: git_repository
                          value: "github.com/Flou21/k8s"
                        - name: git_username
                          value: "Flou21"
                        - name: git_password_secret_name
                          value: "secret"
                        - name: git_password_secret_key
                          value: "password"
                        - name: template_data_deployment_name
                          value: "sky-temp-env-300"
                        - name: template_data_namespace
                          value: "sky"
                        - name: template_data_app_label
                          value: "sky-temp-env-300"
                        - name: template_data_container_tag
                          value: "1ae2c435-abdf-471b-8fff-b2dbe3794d96"
                        - name: template_data_container_image
                          value: "sky-temp-env-300"
                        - name: template_data_container_name
                          value: "sky-temp-env-300"
                        - name: template_data_port
                          value: "8008"
                        - name: template_data_memory
                          value: "100Mi"
                        - name: template_data_cpu
                          value: "100m"
                        - name: template_data_domain_name
                          value: "sky-temp-env-300.flou21.de"