apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-events-ingress
  namespace: argo-events
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /sportdings
        pathType: ImplementationSpecific
        backend:
          service:
            name: sportdings-eventsource-eventsource-svc
            port:
              number: 12000

  - host: argo-events.flou21.de
    http:
      paths:
      - path: /sportdings-frontend
        pathType: ImplementationSpecific
        backend:
          service:
            name: sportdings-frontend-eventsource-eventsource-svc
            port:
              number: 12000
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /sky
        pathType: ImplementationSpecific
        backend:
          service:
            name: sky-eventsource-eventsource-svc
            port:
              number: 12000
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /blog
        pathType: ImplementationSpecific
        backend:
          service:
            name: blog-eventsource-eventsource-svc
            port:
              number: 12000
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /damlo
        pathType: ImplementationSpecific
        backend:
          service:
            name: damlo-eventsource-eventsource-svc
            port:
              number: 12000
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /sky-pull-request
        pathType: ImplementationSpecific
        backend:
          service:
            name: sky-eventsource-eventsource-svc
            port:
              number: 12000
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /sky-frontend
        pathType: ImplementationSpecific
        backend:
          service:
            name: sky-eventsource-eventsource-svc
            port:
              number: 12000
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /static-server
        pathType: ImplementationSpecific
        backend:
          service:
            name: static-server-eventsource-eventsource-svc
            port:
              number: 12000
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /cypress-executor
        pathType: ImplementationSpecific
        backend:
          service:
            name: cypress-executor-eventsource-eventsource-svc
            port:
              number: 12000
  - host: argo-events.flou21.de
    http:
      paths:
      - path: /base-images
        pathType: ImplementationSpecific
        backend:
          service:
            name: base-images-eventsource-eventsource-svc
            port:
              number: 12000

