apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: prom
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grafana.flou21.de
    http:
      paths:
      - path: /
        backend:
          serviceName: loki-grafana
          servicePort: 80