{{ if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openbao.caSecretName | default "openbao-ca" | quote }}
type: Opaque
stringData:
  ca.crt: |
    {{- .Values.openbao.caCert | nindent 4 }}
  {{ end }}