apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: build-container-webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: build-container
    eventSourceName: build-container
    eventName: build-container
    filters:
      data:
      - path: body.git_url
        type: string
        value:
          - "^https://github.com/Coflnet/[A-Za-z0-9_.-]+(.git)?$"
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        parameters:
          - src:
              dependencyName: build-container
              dataKey: body.git_url
            dest: spec.arguments.parameters.0.value
          - src:
              dependencyName: build-container
              dataKey: body.branch
            dest: spec.arguments.parameters.1.value
          - src:
              dependencyName: build-container
              dataKey: body.image
            dest: spec.arguments.parameters.2.value
          - src:
              dependencyName: build-container
              dataKey: body.tag
            dest: spec.arguments.parameters.3.value
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              namespace: argo
              generateName: build-container-
              labels:
                workflows.argoproj.io/archive-strategy: "true"
                security.coflnet.com/k8s-api-access: "false"
            spec:
              workflowTemplateRef:
                name: ci-image-pipeline
              entrypoint: build-only
              arguments:
                parameters:
                  - { name: app_repo, value: "" }
                  - { name: branch, value: "" }
                  - { name: container_image, value: "" }
                  - { name: container_tag, value: "" }
                  - { name: sub_path, value: "." }
                  - { name: git_user, value: "Flou21" }
                  - { name: k8s_file, value: "" }
                  - { name: repo_url, value: "https://github.com/Coflnet/k8s" }
                  - { name: pipeline_start, value: "{{"{{"}}workflow.creationTimestamp.RFC3339{{"}}"}}" }