apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octobox-database-claim
  namespace: octobox
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi