apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: production-test-sky-cron-wf
  namespace: argo
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  serviceAccountName: argo
  workflowSpec:
    entrypoint: production-tests
    imagePullSecrets:
      - name: regcred
    volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    templates:
    - name: production-tests
      dag:
        tasks:
        - name: production-tests
          templateRef:
            name: cypress-tests-chrome91
            template: cypress-tests-chrome91
          arguments: 
            parameters:
              - name: git_repository
                value: "https://github.com/Coflnet/hypixel-react"
              - name: spec 
                value: "cypress/integration/production.spec.ts"
              - name: cypress_base_url
                value: "https://sky-preview.coflnet.com"

        - name: send-mail
          templateRef:
            name: send-mail
            template: send-mail
          arguments: 
            parameters:
              - name: message
                value: "[CI] sky routine production tests failed"
          depends: "production-tests.Failed || production-tests.Errored"
