apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  namespace: sportdings
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
