apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportdings
  namespace: sportdings
  labels:
    app: sportdings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportdings
  template:
    metadata:
      labels:
        app: sportdings
    spec:
      containers:
      - name: sportdings
        image: flou21/sport-dings:3637577a-55a7-47d1-a1b0-12555f3b5700
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: sportdings-service
  namespace: sportdings
spec:
  selector:
    app: sportdings
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80