apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportdings
  namespace: sportdings
  labels:
    app: sportdings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportdings
  template:
    metadata:
      labels:
        app: sportdings
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: sportdings
        image: registry.flou21.de/sport-dings:66a7b9be-64b3-4bd5-b72b-30fe9944a63b
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: sportdings-service
  namespace: sportdings
spec:
  selector:
    app: sportdings
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80