enabled: true
replicaCount: 2

strategy: RollingUpdate

image:
  repository: muehlhansfl/skycrafts
  tag: 532aee992d7c86cc67ce0e0440eb58098ae26bec@sha256:f653f0f9ef0404c07ee931abd0388d8faf96fcd7919893852c86a26d9fa42772
  pullPolicy: IfNotPresent

ports:
  - name: api
    containerPort: 8000

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    memory: 768Mi

serivcePorts:
  - name: api
    port: 8000
    targetPort: 8000

readinessProbe:
  httpGet:
    path: /crafts/ready
    port: api
  initialDelaySeconds: 120
  periodSeconds: 5
