enabled: true
replicaCount: 2

strategy: RollingUpdate

image:
  repository: muehlhansfl/skycrafts
  tag: 9f7bf853a0a4148101a96e05d2209b2773bebee3@sha256:40fa8b0e09622dfbf4181a98f15c09207908ace593d4fd0ee0230892ab75f467
  pullPolicy: IfNotPresent

ports:
  - name: api
    containerPort: 8000

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    memory: 768Mi

serivcePorts:
  - name: api
    port: 8000
    targetPort: 8000

readinessProbe:
  httpGet:
    path: /crafts/ready
    port: api
  initialDelaySeconds: 120
  periodSeconds: 5
