enabled: true
replicaCount: 2

strategy: RollingUpdate

image:
  repository: muehlhansfl/skycrafts
  tag: 4fc360ca7a1f6f9cd7166e0c0499a9c90b70632c@sha256:a96cdff2aaf42f571fe3f8841784726c2b2791e239f324c9cd97b3c407dfa48a
  pullPolicy: IfNotPresent

ports:
  - name: api
    containerPort: 8000

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    memory: 768Mi

serivcePorts:
  - name: api
    port: 8000
    targetPort: 8000

readinessProbe:
  httpGet:
    path: /crafts/ready
    port: api
  initialDelaySeconds: 120
  periodSeconds: 5
