apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: sky
  labels:
    app: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: indexer
        image: registry.flou21.de/sky:fd2cba4d-1fbf-45da-b1fc-36cf3760b413
        ports:
          - containerPort: 8008
        env:
          - name: DBConnection
            valueFrom:
              secretKeyRef:
                key: connection
                name: secret
          - name: apiKey
            valueFrom:
              secretKeyRef:
                key: api
                name: secret
          - name: redisCon
            value: redis-service
          - name: MODE
            value: indexer
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: indexer-service
  namespace: sky
spec:
  selector:
    app: indexer
  ports:
    - port: 8008
      targetPort: 8008