apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: sky
  labels:
    app: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: indexer
        image: registry.flou21.de/sky:e91d1766-a9c8-4934-8d96-c90ede9a68cf
        ports:
          - containerPort: 8008
        env:
          - name: redisCon
            value: redis-service
          - name: apiKey
            valueFrom:
              secretKeyRef:
                key: api
                name: secret
          - name: DBConnection
            valueFrom:
              secretKeyRef:
                key: connection_live
                name: secret
          - name: MODE
            value: indexer
          - name: stripeKey
            valueFrom:
              secretKeyRef:
                key: stripe_key
                name: secret
          - name: stripeSecret
            valueFrom:
              secretKeyRef:
                key: stripe_secret
                name: secret
          - name: firebaseKey
            valueFrom:
              secretKeyRef:
                key: firebase_key
                name: secret
          - name: firebaseSenderId
            valueFrom:
              secretKeyRef:
                key: firebase_sender_id
                name: secret
          - name: PAYPAL_ID
            valueFrom:
              secretKeyRef:
                key: paypal_id
                name: secret
          - name: PAYPAL_SECRET
            valueFrom:
              secretKeyRef:
                key: paypal_secret
                name: secret
        resources:
          requests:
            memory: "1000Mi"
            cpu: "2000m"
        volumeMounts:
          - mountPath: /data
            name: indexer-mount-migration
            subPath: data
      volumes:
        - name: indexer-mount-migration
          persistentVolumeClaim:
            claimName: indexer-claim-migration
---
apiVersion: v1
kind: Service
metadata:
  name: indexer-service
  namespace: sky
spec:
  selector:
    app: indexer
  ports:
    - port: 8008
      targetPort: 8008