apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: sky
  labels:
    app: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: indexer
        image: registry.flou21.de/sky:b4e512b0-a9b5-4e75-a0dc-695b5e6f90e0
        ports:
          - containerPort: 8008
        env:
          - name: DBConnection
            valueFrom:
              secretKeyRef:
                key: connection
                name: secret
          - name: apiKey
            valueFrom:
              secretKeyRef:
                key: api
                name: secret
          - name: redisCon
            value: redis-service
          - name: MODE
            value: indexer
        resources:
          requests:
            memory: "3000Mi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /status
            port: 8008
          initialDelaySeconds: 1000
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: indexer-service
  namespace: sky
spec:
  selector:
    app: indexer
  ports:
    - port: 8008
      targetPort: 8008