apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sky-ingress
  namespace: sky
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sky.flou21.de
    http:
      paths:
      - path: /
        backend:
          serviceName: light-client-service
          servicePort: 8008
  - host: sky-preview.flou21.de
    http:
      paths:
      - path: /
        backend:
          serviceName: light-client-preview-service
          servicePort: 8008
  - host: sky.coflnet.com
    http:
      paths:
      - path: /
        backend:
          serviceName: light-client-service
          servicePort: 8008
  - host: skyblock.coflnet.com
    http:
      paths:
      - path: /
        backend:
          serviceName: light-client-service
          servicePort: 8008
  - host: coflnet.com
    http:
      paths:
      - path: /
        backend:
          serviceName: light-client-service
          servicePort: 8008

