apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: sky
  name: mariadb
spec:
  serviceName: mariadb-service
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3
        args:
          - "--default-authentication-plugin=mysql_native_password"
          - "--innodb-buffer-pool-size=6G"
          - "--key-buffer-size=4G"
          - "--connect-timeout=101"
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "6Gi"
            cpu: "500m"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                key: user
                name: config
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: database
                name: config
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vol
            subPath: data
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: mariadb-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: sky
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
