apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: light-client
  namespace: sky
  labels:
    app: light-client
spec:
  revisionHistoryLimit: 5
  replicas: 5
  progressDeadlineSeconds: 2592000
  selector:
    matchLabels:
      app: light-client
  template:
    metadata:
      labels:
        app: light-client
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: light-client
        image: registry.flou21.de/sky:074edcb2-87b3-4c7a-a9de-33013e2b9a8d
        ports:
          - containerPort: 8008
        env:
          - name: TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                key: token_secret
                name: secret
          - name: DBConnection
            valueFrom:
              secretKeyRef:
                key: connection_live
                name: secret
          - name: redisCon
            value: redis-service
          - name: MODE
            value: light
        resources:
          requests:
            memory: "300Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /status
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
  strategy:
    blueGreen:
      activeService: light-client-service
      previewService: light-client-preview-service
      autoPromotionEnabled: false
      previewReplicaCount: 1
      maxUnavailable: 2
---
apiVersion: v1
kind: Service
metadata:
  name: light-client-service
  namespace: sky
spec:
  selector:
    app: light-client
  ports:
    - port: 8008
      targetPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: light-client-preview-service
  namespace: sky
spec:
  selector:
    app: light-client
  ports:
    - port: 8008
      targetPort: 8008
