apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: sky
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: server
        image: registry.flou21.de/sky:678086d0-6990-4dd6-8752-c78444dd0bcc
        env:
          - name: DBConnection
            valueFrom:
              secretKeyRef:
                key: connection
                name: secret
          - name: redisCon
            value: redis-service
          - name: MODE
            value: light
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: sky
spec:
  selector:
    app: server