apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-frontend
  namespace: sky
  labels:
    app: sky-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sky-frontend
  template:
    metadata:
      labels:
        app: sky-frontend
    spec:
      containers:
      - name: sky-frontend
        image: flou21/hypixel-react:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: sky-frontend-service
  namespace: sky
spec:
  selector:
    app: sky-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
