apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater
  namespace: sky
  labels:
    app: updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: updater
  template:
    metadata:
      labels:
        app: updater
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: updater
        image: registry.flou21.de/sky-core:f226c817-b4c2-4b1e-aa64-7b1a5be8d1df
        env:
        - name: MODE
          value: indexer
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: token_secret
              name: secret
        - name: redisCon
          valueFrom:
            configMapKeyRef: 
              name: config
              key: redis_host
        - name: apiKey
          valueFrom:
            secretKeyRef:
              key: api
              name: secret
        - name: JAEGER_SERVICE_NAME
          valueFrom: 
            configMapKeyRef:
              name: config
              key: jaeger_service_name
        - name: JAEGER_AGENT_HOST
          valueFrom: 
            configMapKeyRef:
              name: config
              key: jaeger_agent_host
        - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
          valueFrom:
            configMapKeyRef:
              name: config
              key: reload_config_on_change
        - name: TOPIC_MISSING_AUCTION
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_missing_auction
        - name: TOPIC_SOLD_AUCTION
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_sold_auction
        - name: TOPIC_NEW_AUCTION
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_new_auction
        - name: TOPIC_AUCTION_ENDED
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_auction_ended
        - name: TOPIC_NEW_BID
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_new_bid
        - name: TOPIC_BAZAAR
          valueFrom: 
            configMapKeyRef:
              name: config
              key: topic_bazaar
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: kafka_host
        resources:
          requests:
            memory: "400Mi"
            cpu: "750m"