apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:3-alpine
        ports:
        - containerPort: 2368
        env:
        - name: database__client
          valueFrom:
            configMapKeyRef:
              key: database__client
              name: config
        - name: database__connection__host
          valueFrom:
            configMapKeyRef:
              key: database__connection__host
              name: config
        - name: database__connection__user
          valueFrom:
            configMapKeyRef:
              key: database__connection__user
              name: config
        - name: database__connection__database
          valueFrom:
            configMapKeyRef:
              key: database__connection__database
              name: config
        - name: url
          valueFrom:
            configMapKeyRef:
              key: url
              name: config
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              key: database__connection__password
              name: secret
        resources:
          limits:
            memory: "800Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost
spec:
  selector:
    app: ghost
  externalName: ghost-service.ghost.svc.cluster.local
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 2368
