apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
