nameOverride: minio
global:
  storageClass: longhorn
existingSecret: minio-secret
resources:
  requests:
    cpu: "300m"
    memory: "500Mi"
ingress:
  enabled: true
  hostname: s3.coflnet.com
  path: /
persistence:
  enabled: true
  storageClass: longhorn
  size: 20Gi