enabled: false
replicaCount: 1

strategy: RollingUpdate

image:
  repository: muehlhansfl/sky-operator
  tag: "v2.0.0@sha256:3dd6b89fe714550e4cadc8a8b5f65b66ef48cb7cad3e29ab6f03680ca12842ce"
  pullPolicy: IfNotPresent

ports:
  - name: metrics
    containerPort: 8080
  - name: probes
    containerPort: 8080
  - name: demo
    containerPort: 80

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    memory: 512Mi

serivcePorts:
  - name: api
    port: 8080
    targetPort: 8080

readinessProbe:
  httpGet:
    path: /
    port: demo
  initialDelaySeconds: 20
  periodSeconds: 3
