apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kafka
data:
  kafka_host: kafka-cluster.kafka.svc.cluster.local
  redis_host: redis-service
  source_topic: sky-raw-flips
  target_topic: sky-flips
  batch_size: "50"
  batch_wait_time: "10"
