apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-dedup-dotnet
  namespace: kafka
  labels:
    app: kafka-dedup-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-dedup-dotnet
  template:
    metadata:
      labels:
        app: kafka-dedup-dotnet
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: kafka-dedup-dotnet
        image: registry.flou21.de/kafka-dedup-dotnet:ce84fd70-054f-48a5-9ec5-bdc8401f4b2a
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"