enabled: true
replicaCount: 3

strategy: RollingUpdate

image:
  repository: muehlhansfl/skyplayerstate
  tag: 1a59ac1e548de53ebc5eea6bca1a51f31c8ac2d8@sha256:055ce17333ea0650522f133ea33f429f939f2ba695043066dec3c7b89dd99043
  pullPolicy: IfNotPresent

ports:
  - name: api
    containerPort: 8000

resources:
  requests:
    cpu: 300m
    memory: 900Mi
  limits:
    memory: 1500Mi

serivcePorts:
  - name: api
    port: 8000
    targetPort: 8000

readinessProbe:
  httpGet:
    path: /api/index.html
    port: api
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 3

envVars:
  # mongo
  - name: Mongo__ConnectionString
    valueFrom:
      secretKeyRef:
        name: secret
        key: mongo_url

  # cassandra

  - name: CASSANDRA__KEYSPACE
    value: sky_item_movement

  - name: SCYLLA__HOSTS
    valueFrom:
      configMapKeyRef:
        name: scylla-config
        key: scylla_host
  - name: SCYLLA__USER
    valueFrom:
      configMapKeyRef:
        name: scylla-config
        key: player_state_user
#  - name: SCYLLA__PASSWORD # loaded from openbao
  - name: SCYLLA__X509Certificate_PATHS
    value: /tls/scylla/secret/db.pfx
  - name: SCYLLA__X509Certificate_PASSWORD
    valueFrom:
      secretKeyRef:
        name: scylla-credentials
        key: db-pfx-password
