replicaCount: 0

strategy: RollingUpdate

enabled: false

image:
  repository: muehlhansfl/accounting
  tag: dcce228c-3d2e-4c9c-b768-3701c9c136f9
  pullPolicy: IfNotPresent

ports: []

resources: 
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 512Mi


serivcePorts: []

envVars:
  - name: JAEGER_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

  - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

  - name: PAYPAL__IS_SANDBOX
    value: "false"

  - name: KAFKA__TLS__CA_LOCATION
    value: "/tls/cm/ca.crt"

  - name: KAFKA__TLS__CERTIFICATE_LOCATION
    value: "/tls/cm/skyblock.crt"

  - name: KAFKA__TLS__KEY_LOCATION
    value: "/tls/secret/skyblock.key"

  - name: KAFKA__REPLICATION_FACTOR
    value: "3"

volumes:
- name: redpanda
  mountPath: /tls/secret
  type: secret
  mountName: redpanda-secret
- name: redpanda
  mountPath: /tls/cm
  type: configmap
  mountName: redpanda-cm

